Rework `Lint/RedundantSafeNavigation` to be more safe
rubocop-hq/rubocop pull request #8884
Opened 2020-10-10 16:52 UTC by fatkodima

Closes #8867 
Closes #8868 

I reworked this to make an offense only when used inside conditions and only for whitelisted methods.

cc @bbatsov @marcandre @natematykiewicz

2020-10-10 17:06 UTC, marcandre requested changes
Good work.

I would remove `nil?` from the allowlist, since `foo&.nil?` is trivially falsey but `foo.nil?` isn't.

Unlikely, but `nil.methods - Object.new.methods #=> [:to_h, :&, :to_c, :to_f, :to_i, :to_a, :to_r, :rationalize, :|, :^]`, so `foo&.respond_to?(any_of_these)` shouldn't be flagged. Because of this, probably best to mark the autocorrect as unsafe (`foo&.respond_to?(variable)` can't be autocorrected safely).

2020-10-10 17:19 UTC, fatkodima commented
Good points 👍 Removed `nil?` and marked as unsafe.

2020-10-10 17:28 UTC, marcandre commented
Great. Would it be difficult to exclude `foo&.respond_to?(:to_a)` and others, when the argument is a literal symbol corresponding to one of the few methods that `NilClass` defines that may not be defined on other objects?

2020-10-10 17:49 UTC, fatkodima commented
Updated with suggestion.
This surely was easy, I just was lazy 😄

2020-10-10 19:59 UTC, marcandre requested changes
Almost ready

2020-10-10 19:59 UTC, marcandre commented on spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
> +                 ^^^^^^^^^^^^^^^^^^^ Redundant safe navigation detected.
Please use `_{loop_type}` (see #8113)

2020-10-10 19:59 UTC, marcandre commented on spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
> +                     ^^^^^^^^^^^^^^^^^^^ Redundant safe navigation detected.
Same here

2020-10-10 19:59 UTC, marcandre commented on config/default.yml
> -  Safe: false
I would keep it as `Safe: false` given that there are some cases can't handle perfectly.

2020-10-10 19:59 UTC, marcandre commented on docs/modules/ROOT/pages/cops_lint.adoc
> +because `NilClass` has methods like `respond_to?` and `is_a?`.
Unsafe examples include: `var = :to_a; foo&.respond_to?(var)` and expressions with `||`/`&&` returning `false` instead of `nil`.

2020-10-10 20:19 UTC, fatkodima commented
@marcandre Thank you for all reviews 💪 
Updated with your suggestions.

2020-10-11 05:31 UTC, bbatsov commented on config/default.yml
> +  AllowedMethods:
You should document this setting in the cop description.

2020-10-11 05:32 UTC, bbatsov commented on lib/rubocop/cop/lint/redundant_safe_navigation.rb
> +      # Unsafe examples include: `var = :to_a; foo&.respond_to?(var)`
Isn't it better to drop a code block with unsafe examples here?

2020-10-11 10:19 UTC, fatkodima commented
Updated with suggestions. Let me know if there is anything else I can improve.

2020-10-12 06:23 UTC, merged

2020-10-12 06:23 UTC, bbatsov commented
Thanks!