Add `RegexpRegexp::Expression#loc` and `#expression`. Deprecate `parsed_tree_expr_loc`
rubocop-hq/rubocop pull request #8960
Opened 2020-10-27 21:06 UTC by marcandre

The source information provided by `regexp_parser` is difficult to use.

This PR adds a `parser`-like location map to these nodes. E.g.:

```
[a-z]{2,}
^^^^^^^^^ expression
     ^^^^ quantifier
^^^^^     body
^         begin
    ^     end
```

Will be useful for #8948

2020-10-27 21:23 UTC, marcandre commented
cc/ @owst

2020-10-27 23:16 UTC, marcandre commented on changelog/new_add_regexpregexpexpressionloc_and.md
> +* [#8960](https://github.com/rubocop-hq/rubocop/pull/8960): Add `RegexpRegexp::Expression#loc` and `#expression`. Deprecate `parsed_tree_expr_loc`. ([@marcandre][])
Oops, thanks

2020-10-27 23:16 UTC, marcandre commented on lib/rubocop/ext/regexp_node.rb
> +      # @deprecated Use `expression`, or `loc.body`
Ah, in this case yes, perfect.

2020-10-27 23:16 UTC, marcandre commented on lib/rubocop/ext/regexp_parser.rb
> +          @begin, @end = begin_end.values_at(:begin, :end)
yeah. I don't know why I come up with these things, that's a bit silly. Let me simply this

2020-10-27 23:31 UTC, owst requested changes

2020-10-27 23:31 UTC, owst commented on changelog/new_add_regexpregexpexpressionloc_and.md
> +* [#8960](https://github.com/rubocop-hq/rubocop/pull/8960): Add `RegexpRegexp::Expression#loc` and `#expression`. Deprecate `parsed_tree_expr_loc`. ([@marcandre][])
Typo here still - but also now need to reword "Deprecate ..."

2020-10-27 23:55 UTC, owst commented
LGTM 👍

2020-10-28 00:36 UTC, marcandre commented
Thanks for the quick review @owst 💛

2020-10-28 08:04 UTC, bbatsov commented
Nice improvement!

2020-10-28 08:04 UTC, merged